Update after own review
xlqian/navitia pull request #6
Opened 2018-07-13 14:44 UTC by pbougue

Tried to separate commits between easy (just renaming and so) and more controversial decision (so it's easier to revert)

2018-07-13 16:52 UTC, TeXitoi requested changes

2018-07-13 16:52 UTC, TeXitoi commented on source/jormungandr/tests/journey_common_tests.py
> +                                                                    min_nb_journeys='20',
no quote

2018-07-13 16:52 UTC, TeXitoi commented on source/jormungandr/tests/journey_common_tests.py
> +                                                                    min_nb_journeys='21',
no quote

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/raptor_api.cpp
> +                                       const boost::optional<DateTime>& timeframe_limit,
I think uint32_t is better that DateTime here.

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/raptor_api.cpp
> +        auto is_inside = [&clockwise](const routing::Journey& j, DateTime dt){
why?

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/tests/routing_api_test.cpp
> +    // timeframe_duration = 10*60*2 (20 min)
20*60?

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/tests/routing_api_test.cpp
>      // timeframe_max_datetime = 86400 (24H)
What's that?

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/tests/routing_api_test.cpp
>      timeframe_duration = 60*60*1;  // 1H
You can also correct that

2018-07-13 16:52 UTC, TeXitoi commented on source/routing/tests/routing_api_test.cpp
> +                  timeframe_max_datetime,
That's not a datetime

2018-07-16 07:46 UTC, mbounabi requested changes

2018-07-16 07:46 UTC, mbounabi commented on source/jormungandr/tests/journey_common_tests.py
> +    '''
PEP 257 : For consistency, always use """triple double quotes"""
I won't put a comment on every changes but please revert this

2018-07-16 08:05 UTC, pbougue commented on source/routing/raptor_api.cpp
> +                                       const boost::optional<DateTime>& timeframe_limit,
I do not agree (or I didn't understand why DateTime are for).
This is a DateTime in Navitia's semantics, not a duration, so I think it's better.

2018-07-16 08:20 UTC, TeXitoi commented on source/routing/raptor_api.cpp
> +                                       const boost::optional<DateTime>& timeframe_limit,
My bad.

2018-07-16 08:31 UTC, xlqian approved these changes

2018-07-16 08:32 UTC, merged